author: Luis Ezcurdia
title: Luis Ezcurdia
email: ing.ezcurdia@gmail.com
description: I love to build stuff
url: http://ezcurdia.dev/

markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  stories:
    output: true
    permalink: /stories/:slug/

feed:
  path: atom.xml

social:
  github: 3zcurdia
  twitter: 3zcurdia
  linkedin: 3zcurdia

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - AGENTS.md
  - LICENSE
