author: Luis Ezcurdia
title: Luis Ezcurdia
email: ing.ezcurdia@gmail.com
description: I like to build things
url: http://ezcurdia.dev/

markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

social:
  github: 3zcurdia
  twitter: 3zcurdia
  linkedin: 3zcurdia

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - AGENTS.md
  - LICENSE
